import { Coupon } from "../models/coupon.models.js";

async function addCoupon() {
  try {
    const coupons = [
      {
        couponCode: "FIRSTRIDE",
        couponImage: "firstride.jpg",
        description: "Get 15% off on your first booking.",
        discountType: "PERCENTAGE",
        discountValue: 15,
        maxDiscountAmount: 300,
        minOrderAmount: 400,
        usageLimitTotal: 10000,
        usageLimitPerUser: 1,
        usedCount: 2150,
        offerStarts: new Date("2026-01-01"),
        offerEnds: new Date("2026-12-31"),
        isActive: true,
      },
      {
        couponCode: "FLAT150",
        couponImage: "flat150.jpg",
        description: "Flat ₹150 off on all rides.",
        discountType: "FLAT",
        discountValue: 150,
        maxDiscountAmount: null,
        minOrderAmount: 600,
        usageLimitTotal: 5000,
        usageLimitPerUser: 2,
        usedCount: 1240,
        offerStarts: new Date("2026-02-01"),
        offerEnds: new Date("2026-11-30"),
        isActive: true,
      },
      {
        couponCode: "NIGHTOWL",
        couponImage: "nightowl.jpg",
        description: "10% cashback on night trips.",
        discountType: "PERCENTAGE",
        discountValue: 10,
        maxDiscountAmount: 200,
        minOrderAmount: 500,
        usageLimitTotal: 2000,
        usageLimitPerUser: 3,
        usedCount: 480,
        offerStarts: new Date("2026-03-01"),
        offerEnds: new Date("2026-10-31"),
        isActive: true,
      },
      {
        couponCode: "WEEKEND15",
        couponImage: "weekend15.jpg",
        description: "15% off on weekend travel.",
        discountType: "PERCENTAGE",
        discountValue: 15,
        maxDiscountAmount: 250,
        minOrderAmount: 800,
        usageLimitTotal: 10000,
        usageLimitPerUser: 3,
        usedCount: 3200,
        offerStarts: new Date("2026-04-01"),
        offerEnds: new Date("2026-06-30"),
        isActive: false,
      },
      {
        couponCode: "PREMIUM500",
        couponImage: "premium500.jpg",
        description: "Flat ₹500 off on premium bookings.",
        discountType: "FLAT",
        discountValue: 500,
        maxDiscountAmount: null,
        minOrderAmount: 3000,
        usageLimitTotal: 500,
        usageLimitPerUser: 1,
        usedCount: 89,
        offerStarts: new Date("2026-09-15"),
        offerEnds: new Date("2026-11-15"),
        isActive: true,
      },
      {
        couponCode: "EARLYBIRD",
        couponImage: "earlybird.jpg",
        description: "20% off for early morning trips.",
        discountType: "PERCENTAGE",
        discountValue: 20,
        maxDiscountAmount: 350,
        minOrderAmount: 1000,
        usageLimitTotal: null,
        usageLimitPerUser: 5,
        usedCount: 720,
        offerStarts: new Date("2026-05-01"),
        offerEnds: new Date("2026-12-31"),
        isActive: true,
      },
      {
        couponCode: "FLAT75",
        couponImage: "flat75.jpg",
        description: "Flat ₹75 off on bookings above ₹500.",
        discountType: "FLAT",
        discountValue: 75,
        maxDiscountAmount: null,
        minOrderAmount: 500,
        usageLimitTotal: null,
        usageLimitPerUser: 1,
        usedCount: 4500,
        offerStarts: new Date("2026-01-01"),
        offerEnds: new Date("2026-12-31"),
        isActive: true,
      },
      {
        couponCode: "MEGA25",
        couponImage: "mega25.jpg",
        description: "25% off up to ₹400.",
        discountType: "PERCENTAGE",
        discountValue: 25,
        maxDiscountAmount: 400,
        minOrderAmount: 1500,
        usageLimitTotal: 3000,
        usageLimitPerUser: 2,
        usedCount: 980,
        offerStarts: new Date("2026-07-01"),
        offerEnds: new Date("2026-09-30"),
        isActive: true,
      },
      {
        couponCode: "FLASH50",
        couponImage: "flash50.jpg",
        description: "Flat ₹50 off on bookings above ₹400.",
        discountType: "FLAT",
        discountValue: 50,
        maxDiscountAmount: null,
        minOrderAmount: 400,
        usageLimitTotal: 1000,
        usageLimitPerUser: 1,
        usedCount: 850,
        offerStarts: new Date("2026-06-01"),
        offerEnds: new Date("2026-06-15"),
        isActive: false,
      },
      {
        couponCode: "ALLRIDE10",
        couponImage: "allride10.jpg",
        description: "10% off on all bus bookings.",
        discountType: "PERCENTAGE",
        discountValue: 10,
        maxDiscountAmount: 150,
        minOrderAmount: 0,
        usageLimitTotal: null,
        usageLimitPerUser: 10,
        usedCount: 5600,
        offerStarts: new Date("2026-01-01"),
        offerEnds: new Date("2026-12-31"),
        isActive: true,
      },
    ];
    if (await Coupon.countDocuments() <= 10) {
      const response = await Coupon.insertMany(coupons);
      if (response) {
        console.log('Coupons added successfully');
      }
    } else {
      console.log("Coupons already exist. Skipping insertion");
      return;
    }
  } catch (error) {
    console.error(`Failed to add new coupon: ${error.message}`);
  }
}

export default addCoupon;
